# Generated by Django 2.2.4 on 2019-09-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_table_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_table_date', to='rest.TableDate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_table', to='rest.Table'),
        ),
    ]
