# Generated by Django 2.2.4 on 2019-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190929_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledate',
            name='table',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_table_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='visitor table date reserve'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
        migrations.DeleteModel(
            name='TableDate',
        ),
    ]
