# Generated by Django 2.2.4 on 2019-10-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20191017_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Столик', 'verbose_name_plural': 'Столики'},
        ),
    ]
